name: CPP project with Catch2 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: clang
      CXX: clang++

    steps:
    - name: Setup dependencies
      run: sudo apt-get install -y clang-tidy

    - name: Checkout submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

#    - name: Build default
#      run: mkdir build && cmake -S. -Bbuild -DUSE_CLANG_TIDY=TRUE -DTESTS_BUILD_TYPE=NONE -DCMAKE_BUILD_TYPE=Release && cmake --build build
#    - name: Run fractal tests
#      timeout-minutes: 10
#      working-directory: ./build/lib/fractal
#      run: ./FractalTests
#
#    - name: Build ASAN
#      run: mkdir build_ASAN && cmake -S. -Bbuild_ASAN -DTESTS_BUILD_TYPE=ASAN -DCMAKE_BUILD_TYPE=Debug && cmake --build build_ASAN
#    - name: Run ASAN Int128 tests
#      timeout-minutes: 15
#      working-directory: ./build/lib/fractal
#      run: ./FractalTests
#
#    - name: Build USAN
#      run: mkdir build_USAN && cmake -S. -Bbuild_USAN -DTESTS_BUILD_TYPE=USAN -DCMAKE_BUILD_TYPE=Debug && cmake --build build_USAN
#    - name: Run USAN Int128 tests
#      timeout-minutes: 15
#      working-directory: ./build/lib/fractal
#      run: ./FractalTests